version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: zinhack_back
    environment:
      SERVER_ADDRESS: "0.0.0.0:8080"
      SERVER_ENV: "dev"

      # PostgreSQL
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: zinhack
      DB_PASS: zinhack
      DB_NAME: zinhack

      # Redis
      REDIS_HOST: redis
      REDIS_PORT: "6379"

      # MinIO (s3 совместимое хранилище)
      S3_ENDPOINT: "minio:9000"
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_BUCKET: mybucket
      S3_USE_SSL: "false"
    ports:
      - "6611:8080"
    networks:
      - backend_network
    depends_on:
      - db
      - redis
      - minio
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: zinhack_postgres_db
    environment:
      POSTGRES_USER: zinhack
      POSTGRES_PASSWORD: zinhack
      POSTGRES_DB: zinhack
    ports:
      - "6612:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zinhack"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: zinhack_redis_cache
    ports:
      - "6613:6379"
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  minio:
    image: minio/minio
    container_name: zin_hack_minio_storage
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "6614:9000"
      - "6615:9001"
    volumes:
      - minio_data:/data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  minio_data:

networks:
  backend_network:
    driver: bridge