name: CI/CD Backend Pipeline

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: ghcr.io/${{ secrets.GHCR_USERNAME }}/zinhack-backend:latest

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push image
        run: docker push $IMAGE_NAME

  test:
    name: Test Compose Locally
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Pull backend image
        run: docker pull $IMAGE_NAME

      - name: Override image в docker-compose.yml (временный патч)
        run: |
          sed -i 's|build:.*|image: '"$IMAGE_NAME"'|' docker-compose.yml

      - name: Launch services
        run: docker compose up -d

      - name: Wait for backend
        run: sleep 5

      - name: Test /ping endpoint
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:6611/api/v1/ping)
          echo "Status code: $STATUS"
          if [ "$STATUS" != "200" ]; then
            echo "Ping failed, dumping logs..."
            docker compose logs app
            exit 1
          fi

      - name: Stop containers after test
        run: docker compose down

  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Install SSH client
        run: sudo apt-get install -y sshpass

      - name: Deploy via SSH
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} <<'EOF'
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

            cd ~/zin_hack_backend || exit 1

            docker compose down || true
            docker compose pull
            docker compose up -d

            echo "Wait 3s and check ping..."
            sleep 3
            curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/api/v1/ping
